import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "./context/store";
import Footer from "./components/Footer";

const leagueSpartan = League_Spartan({
  weight: ["700", "600", "400", "300"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Dine Restaurant",
    template: "%s | Dine Restaurant",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GlobalContextProvider>
      <html lang="en">
        <body className={leagueSpartan.className}>
          {children}
          <Footer />
        </body>
      </html>
    </GlobalContextProvider>
  );
}
